# Generated by Django 2.0.13 on 2019-04-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourrelated', '0002_auto_20190405_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourrelated.Tour')),
            ],
        ),
    ]
