# Generated by Django 2.0.13 on 2019-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourrelated', '0003_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
