# Generated by Django 2.0.13 on 2019-04-05 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tourrelated', '0006_finance_board_expens'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
